linters-settings:
  gci:
    max-len: 120
    line-length: 120

run:
  timeout: 5m

issues:
  exclude-dirs:
    - vendor
    - bundle
    - hack
    - img

linters:
  enable:
    - gci
    - goconst
    - gocritic
    - govet
    - gofmt
    - unused
    - cyclop